ENVIRONMENT:
  MAX_EPISODE_STEPS: 500

SIMULATOR:
  TURN_ANGLE: 30
  TILT_ANGLE: 30
  ACTION_SPACE_CONFIG: "v1"
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
    HEIGHT: 0.88
    RADIUS: 0.18
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False
  SEMANTIC_SENSOR:
    WIDTH: 480
    HEIGHT: 640
    HFOV: 42
    POSITION: [0, 1.31, 0]
  RGB_SENSOR:
    WIDTH: 480
    HEIGHT: 640
    HFOV: 42
    POSITION: [0, 1.31, 0]
  DEPTH_SENSOR:
    WIDTH: 480
    HEIGHT: 640
    HFOV: 42
    MIN_DEPTH: 0.5
    MAX_DEPTH: 4.0
    POSITION: [0, 1.31, 0]
TASK:
  TYPE: ObjectNav-v1
  POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT", "LOOK_UP", "LOOK_DOWN"]

  SENSORS: ['OBJECTGOAL_SENSOR', 'COMPASS_SENSOR', 'GPS_SENSOR']
  GOAL_SENSOR_UUID: objectgoal

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL']

  DISTANCE_TO_GOAL:
    DISTANCE_TO: VIEW_POINTS
  SUCCESS:
    SUCCESS_DISTANCE: 0.1

DATASET:
  TYPE: ObjectNav-v1
  SPLIT: val_mini
  DATA_PATH: "habitat-challenge-data/data/datasets/objectnav/hm3d/{split}/{split}.json.gz"
  SCENES_DIR: "habitat-challenge-data/data/scene_datasets/"